# Compiler and Linker
CC      = clang
LD      = $(CC)

# -pedantic \
# -Wextra \
# -Wformat-security \
# -Wfloat-equal \
# -Wshadow \
# -Wconversion \
# -Wjump-misses-init \
# -Wlogical-not-parentheses \
# -Wnull-dereference \
# -Wvla \


# Directories
SRC_DIR = src
BUILD_DIR = build
TIMBR_DIR = timbr

# Flags
CFLAGS  = -g -O3 -Wall -Wno-unused-parameter -march=native -funroll-loops -std=c11 -D_POSIX_C_SOURCE=200809L \
          -I include/ -I $(TIMBR_DIR) $(shell llvm-config --cflags) \
          -MMD -MP

# Header dependency files (generated by -MMD) so editing a header rebuilds
# every object that includes it -- token enum shifts otherwise leave stale
# objects comparing against old constant values. NB: OBJS also carries
# timbr/timbr.c verbatim (clang compiles it straight off the link line),
# which must be filtered out or -include would parse the C file as a
# makefile.
DEPS = $(patsubst %.o,%.d,$(filter %.o,$(OBJS)))

LDFLAGS = $(shell llvm-config --ldflags --link-shared --libs --system-libs \
            core executionengine analysis native passes coroutines bitwriter)

# Files
SRCS      = $(wildcard $(SRC_DIR)/*.c) $(TIMBR_DIR)/timbr.c
CGEN_SRCS = $(wildcard $(SRC_DIR)/codegen/*.c)
OBJS      = $(patsubst $(SRC_DIR)/%.c,$(BUILD_DIR)/%.o,$(SRCS)) \
            $(patsubst $(SRC_DIR)/codegen/%.c,$(BUILD_DIR)/codegen_%.o,$(CGEN_SRCS))
TARGET = kawac

# Pretty Colors
GREEN  := \033[1;32m
BLUE   := \033[1;34m
YELLOW := \033[1;33m
RESET  := \033[0m

all: $(TARGET)

-include $(DEPS)

$(TARGET): $(OBJS)
	@echo "$(BLUE)[Linking]$(RESET) $@"
	@$(LD) $(OBJS) -o $@ $(LDFLAGS)
	@echo "$(GREEN)[Done]$(RESET) Built $@"

# Build object files in build/
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c | $(BUILD_DIR)
	@echo "$(YELLOW)[Compiling]$(RESET) $<"
	@$(CC) $(CFLAGS) -c $< -o $@

# Build codegen submodule files
$(BUILD_DIR)/codegen_%.o: $(SRC_DIR)/codegen/%.c | $(BUILD_DIR)
	@echo "$(YELLOW)[Compiling]$(RESET) $<"
	@$(CC) $(CFLAGS) -I $(SRC_DIR)/codegen -c $< -o $@

# timbr lives outside src/; without an explicit rule make falls back to a
# builtin pattern whose -MMD/-MP output confuses it.
$(BUILD_DIR)/timbr_timbr.o: $(TIMBR_DIR)/timbr.c | $(BUILD_DIR)
	@echo "$(YELLOW)[Compiling]$(RESET) $<"
	@$(CC) $(CFLAGS) -c $< -o $@

# Create build directory if missing
$(BUILD_DIR):
	@mkdir -p $(BUILD_DIR)

clean:
	@echo "$(YELLOW)[Cleaning]$(RESET)"
	@rm -rf $(BUILD_DIR) $(TARGET) *.ll *.bc
	@echo "$(GREEN)[Clean complete]$(RESET)"

.PHONY: all clean debug
