#!/usr/bin/env python3
"""Generate an embedded bitcode header using the compiler's own LLVM version."""
import argparse
import pathlib
import subprocess
import tempfile

p = argparse.ArgumentParser()
p.add_argument('--clang', required=True)
p.add_argument('--source', required=True)
p.add_argument('--output', required=True)
p.add_argument('--symbol', default='kawa_memory_bc')
p.add_argument('--metrics', action='store_true')
a = p.parse_args()
with tempfile.TemporaryDirectory(prefix='kawa-runtime-') as d:
    bc = pathlib.Path(d) / 'runtime.bc'
    # kawac currently emits for the native host, like its own native build.
    # Match the C benchmark's CPU and optimization policy in the embedded
    # runtime instead of retaining generic CPU attributes from clang.
    subprocess.run([a.clang, '-std=c11', '-O3', '-march=native', '-fPIC', '-emit-llvm', '-c',
                    *(['-DKAWA_MEMORY_METRICS'] if a.metrics else []),
                    a.source, '-o', str(bc)], check=True)
    data = bc.read_bytes()
out = pathlib.Path(a.output)
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text('/* Generated by scripts/embed_runtime.py. */\n'
               f'static const unsigned char {a.symbol}[] = {{\n' +
               '\n'.join(','.join(f'0x{b:02x}' for b in data[i:i+24])+','
                         for i in range(0, len(data), 24)) +
               f'\n}};\nstatic const unsigned long {a.symbol}_len = sizeof({a.symbol});\n')
